version: '3.4'

services:
  db:
    image: postgres:15.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  payment_api:
    build:
      context: ./payment_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8090:8000"

volumes:
  postgres_volume:
