version: '3.4'

services:
  db:
    image: postgres:15.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  payment_api:
    build:
      context: ./payment_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8090:8000"

  auth_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .auth_env

  auth_redis:
    image: redis:6.0.9
    restart: on-failure

  auth_api:
    build: ./auth/auth_api
    env_file:
      - .auth_env
    expose:
      - "8000"
    ports:
      - "8999:8000"
    volumes:
      - /tmp/logs/app/json:/var/log/app
    depends_on:
      - auth_redis
      - auth_db

volumes:
  postgres_volume:
  postgres_data:
