version: '3.4'

services:
  db:
    image: postgres:15.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
  
  payment_api:
    build:
      context: ./payment_api
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db

  auth_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .auth_env

  redis:
    image: redis:6.0.9
    restart: on-failure

  auth_api:
    build: ./auth/auth_api
    env_file:
      - .auth_env
    volumes:
      - /tmp/logs/app/json:/var/log/app
    expose:
      - "8000"
    depends_on:
      - redis
      - auth_db

  payment-manager:
    container_name: payment-manager
    build: payment_manager/
    env_file:
      - ./.env
    depends_on:
      - payment_api
      - auth_api

  scheduler:
    build: ./scheduler/
    depends_on:
      - redis
    env_file:
      - ./scheduler/.env

  nginx:
    container_name: proxy-server
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - payment_api
    ports:
      - 8000:80

volumes:
  postgres_volume:
  postgres_data:

networks:
  default:
    name: graduate_network
    external: true
